# Generated by Django 3.1.3 on 2020-12-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='date',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
