# Generated by Django 3.1.3 on 2020-12-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201217_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
