# Generated by Django 3.1.3 on 2020-12-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201221_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_url',
        ),
    ]
