# Generated by Django 3.1.3 on 2020-12-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20201231_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
